Insert into country_info values('AFG','Afghanistan');
Insert into country_info values('ALB','Albania');
Insert into country_info values('DZA','Algeria');
Insert into country_info values('ASM','American Samoa');
Insert into country_info values('AND','Andorra');
Insert into country_info values('AGO','Angola');
Insert into country_info values('AIA','Anguilla');
Insert into country_info values('ATA','Antarctica');
Insert into country_info values('ATG','Antigua and Barbuda');
Insert into country_info values('ARG','Argentina');
Insert into country_info values('ARM','Armenia');
Insert into country_info values('ABW','Aruba');
Insert into country_info values('AUS','Australia');
Insert into country_info values('AUT','Austria');
Insert into country_info values('AZE','Azerbaijan');
Insert into country_info values('BHS','Bahamas');
Insert into country_info values('BHR','Bahrain');
Insert into country_info values('BGD','Bangladesh');
Insert into country_info values('BRB','Barbados');
Insert into country_info values('BLR','Belarus');
Insert into country_info values('BEL','Belgium');
Insert into country_info values('BLZ','Belize');
Insert into country_info values('BEN','Benin');
Insert into country_info values('BMU','Bermuda');
Insert into country_info values('BTN','Bhutan');
Insert into country_info values('BOL','Bolivia');
Insert into country_info values('BIH','Bosnia and Herzegovina');
Insert into country_info values('BWA','Botswana');
Insert into country_info values('BRA','Brazil');
Insert into country_info values('IOT','British Indian Ocean Territory');
Insert into country_info values('VGB','British Virgin Islands');
Insert into country_info values('BRN','Brunei');
Insert into country_info values('BGR','Bulgaria');
Insert into country_info values('BFA','Burkina Faso');
Insert into country_info values('BDI','Burundi');
Insert into country_info values('KHM','Cambodia');
Insert into country_info values('CMR','Cameroon');
Insert into country_info values('CAN','Canada');
Insert into country_info values('CPV','Cape Verde');
Insert into country_info values('CYM','Cayman Islands');
Insert into country_info values('CAF','Central African Republic');
Insert into country_info values('TCD','Chad');
Insert into country_info values('CHL','Chile');
Insert into country_info values('CHN','China');
Insert into country_info values('CXR','Christmas Island');
Insert into country_info values('CCK','Cocos Islands');
Insert into country_info values('COL','Colombia');
Insert into country_info values('COM','Comoros');
Insert into country_info values('COK','Cook Islands');
Insert into country_info values('CRI','Costa Rica');
Insert into country_info values('HRV','Croatia');
Insert into country_info values('CUB','Cuba');
Insert into country_info values('CUW','Curacao');
Insert into country_info values('CYP','Cyprus');
Insert into country_info values('CZE','Czech Republic');
Insert into country_info values('COD','Democratic Republic of the Congo');
Insert into country_info values('DNK','Denmark');
Insert into country_info values('DJI','Djibouti');
Insert into country_info values('DMA','Dominica');
Insert into country_info values('DOM','Dominican Republic');
Insert into country_info values('TLS','East Timor');
Insert into country_info values('ECU','Ecuador');
Insert into country_info values('EGY','Egypt');
Insert into country_info values('SLV','El Salvador');
Insert into country_info values('GNQ','Equatorial Guinea');
Insert into country_info values('ERI','Eritrea');
Insert into country_info values('EST','Estonia');
Insert into country_info values('ETH','Ethiopia');
Insert into country_info values('FLK','Falkland Islands');
Insert into country_info values('FRO','Faroe Islands');
Insert into country_info values('FJI','Fiji');
Insert into country_info values('FIN','Finland');
Insert into country_info values('FRA','France');
Insert into country_info values('PYF','French Polynesia');
Insert into country_info values('GAB','Gabon');
Insert into country_info values('GMB','Gambia');
Insert into country_info values('GEO','Georgia');
Insert into country_info values('DEU','Germany');
Insert into country_info values('GHA','Ghana');
Insert into country_info values('GIB','Gibraltar');
Insert into country_info values('GRC','Greece');
Insert into country_info values('GRL','Greenland');
Insert into country_info values('GRD','Grenada');
Insert into country_info values('GUM','Guam');
Insert into country_info values('GTM','Guatemala');
Insert into country_info values('GGY','Guernsey');
Insert into country_info values('GIN','Guinea');
Insert into country_info values('GNB','Guinea-Bissau');
Insert into country_info values('GUY','Guyana');
Insert into country_info values('HTI','Haiti');
Insert into country_info values('HND','Honduras');
Insert into country_info values('HKG','Hong Kong');
Insert into country_info values('HUN','Hungary');
Insert into country_info values('ISL','Iceland');
Insert into country_info values('IND','India');
Insert into country_info values('IDN','Indonesia');
Insert into country_info values('IRN','Iran');
Insert into country_info values('IRQ','Iraq');
Insert into country_info values('IRL','Ireland');
Insert into country_info values('IMN','Isle of Man');
Insert into country_info values('ISR','Israel');
Insert into country_info values('ITA','Italy');
Insert into country_info values('CIV','Ivory Coast');
Insert into country_info values('JAM','Jamaica');
Insert into country_info values('JPN','Japan');
Insert into country_info values('JEY','Jersey');
Insert into country_info values('JOR','Jordan');
Insert into country_info values('KAZ','Kazakhstan');
Insert into country_info values('KEN','Kenya');
Insert into country_info values('KIR','Kiribati');
Insert into country_info values('XKX','Kosovo');
Insert into country_info values('KWT','Kuwait');
Insert into country_info values('KGZ','Kyrgyzstan');
Insert into country_info values('LAO','Laos');
Insert into country_info values('LVA','Latvia');
Insert into country_info values('LBN','Lebanon');
Insert into country_info values('LSO','Lesotho');
Insert into country_info values('LBR','Liberia');
Insert into country_info values('LBY','Libya');
Insert into country_info values('LIE','Liechtenstein');
Insert into country_info values('LTU','Lithuania');
Insert into country_info values('LUX','Luxembourg');
Insert into country_info values('MAC','Macau');
Insert into country_info values('MKD','Macedonia');
Insert into country_info values('MDG','Madagascar');
Insert into country_info values('MWI','Malawi');
Insert into country_info values('MYS','Malaysia');
Insert into country_info values('MDV','Maldives');
Insert into country_info values('MLI','Mali');
Insert into country_info values('MLT','Malta');
Insert into country_info values('MHL','Marshall Islands');
Insert into country_info values('MRT','Mauritania');
Insert into country_info values('MUS','Mauritius');
Insert into country_info values('MYT','Mayotte');
Insert into country_info values('MEX','Mexico');
Insert into country_info values('FSM','Micronesia');
Insert into country_info values('MDA','Moldova');
Insert into country_info values('MCO','Monaco');
Insert into country_info values('MNG','Mongolia');
Insert into country_info values('MNE','Montenegro');
Insert into country_info values('MSR','Montserrat');
Insert into country_info values('MAR','Morocco');
Insert into country_info values('MOZ','Mozambique');
Insert into country_info values('MMR','Myanmar');
Insert into country_info values('NAM','Namibia');
Insert into country_info values('NRU','Nauru');
Insert into country_info values('NPL','Nepal');
Insert into country_info values('NLD','Netherlands');
Insert into country_info values('ANT','Netherlands Antilles');
Insert into country_info values('NCL','New Caledonia');
Insert into country_info values('NZL','New Zealand');
Insert into country_info values('NIC','Nicaragua');
Insert into country_info values('NER','Niger');
Insert into country_info values('NGA','Nigeria');
Insert into country_info values('NIU','Niue');
Insert into country_info values('PRK','North Korea');
Insert into country_info values('MNP','Northern Mariana Islands');
Insert into country_info values('NOR','Norway');
Insert into country_info values('OMN','Oman');
Insert into country_info values('PAK','Pakistan');
Insert into country_info values('PLW','Palau');
Insert into country_info values('PSE','Palestine');
Insert into country_info values('PAN','Panama');
Insert into country_info values('PNG','Papua New Guinea');
Insert into country_info values('PRY','Paraguay');
Insert into country_info values('PER','Peru');
Insert into country_info values('PHL','Philippines');
Insert into country_info values('PCN','Pitcairn');
Insert into country_info values('POL','Poland');
Insert into country_info values('PRT','Portugal');
Insert into country_info values('PRI','Puerto Rico');
Insert into country_info values('QAT','Qatar');
Insert into country_info values('COG','Republic of the Congo');
Insert into country_info values('REU','Reunion');
Insert into country_info values('ROU','Romania');
Insert into country_info values('RUS','Russia');
Insert into country_info values('RWA','Rwanda');
Insert into country_info values('BLM','Saint Barthelemy');
Insert into country_info values('SHN','Saint Helena');
Insert into country_info values('KNA','Saint Kitts and Nevis');
Insert into country_info values('LCA','Saint Lucia');
Insert into country_info values('MAF','Saint Martin');
Insert into country_info values('SPM','Saint Pierre and Miquelon');
Insert into country_info values('VCT','Saint Vincent and the Grenadines');
Insert into country_info values('WSM','Samoa');
Insert into country_info values('SMR','San Marino');
Insert into country_info values('STP','Sao Tome and Principe');
Insert into country_info values('SAU','Saudi Arabia');
Insert into country_info values('SEN','Senegal');
Insert into country_info values('SRB','Serbia');
Insert into country_info values('SYC','Seychelles');
Insert into country_info values('SLE','Sierra Leone');
Insert into country_info values('SGP','Singapore');
Insert into country_info values('SXM','Sint Maarten');
Insert into country_info values('SVK','Slovakia');
Insert into country_info values('SVN','Slovenia');
Insert into country_info values('SLB','Solomon Islands');
Insert into country_info values('SOM','Somalia');
Insert into country_info values('ZAF','South Africa');
Insert into country_info values('KOR','South Korea');
Insert into country_info values('SSD','South Sudan');
Insert into country_info values('ESP','Spain');
Insert into country_info values('LKA','Sri Lanka');
Insert into country_info values('SDN','Sudan');
Insert into country_info values('SUR','Suriname');
Insert into country_info values('SJM','Svalbard and Jan Mayen');
Insert into country_info values('SWZ','Swaziland');
Insert into country_info values('SWE','Sweden');
Insert into country_info values('CHE','Switzerland');
Insert into country_info values('SYR','Syria');
Insert into country_info values('TWN','Taiwan');
Insert into country_info values('TJK','Tajikistan');
Insert into country_info values('TZA','Tanzania');
Insert into country_info values('THA','Thailand');
Insert into country_info values('TGO','Togo');
Insert into country_info values('TKL','Tokelau');
Insert into country_info values('TON','Tonga');
Insert into country_info values('TTO','Trinidad and Tobago');
Insert into country_info values('TUN','Tunisia');
Insert into country_info values('TUR','Turkey');
Insert into country_info values('TKM','Turkmenistan');
Insert into country_info values('TCA','Turks and Caicos Islands');
Insert into country_info values('TUV','Tuvalu');
Insert into country_info values('VIR','U.S. Virgin Islands');
Insert into country_info values('UGA','Uganda');
Insert into country_info values('UKR','Ukraine');
Insert into country_info values('ARE','United Arab Emirates');
Insert into country_info values('GBR','United Kingdom');
Insert into country_info values('USA','United States');
Insert into country_info values('URY','Uruguay');
Insert into country_info values('UZB','Uzbekistan');
Insert into country_info values('VUT','Vanuatu');
Insert into country_info values('VAT','Vatican');
Insert into country_info values('VEN','Venezuela');
Insert into country_info values('VNM','Vietnam');
Insert into country_info values('WLF','Wallis and Futuna');
Insert into country_info values('ESH','Western Sahara');
Insert into country_info values('YEM','Yemen');
Insert into country_info values('ZMB','Zambia');
Insert into country_info values('ZWE','Zimbabwe');

-- DELETE FROM country_info;
select * from country_info;
-- DESC COUNTRY_INFO;