select * from course_sub_rel;
desc course_sub_rel;
Insert into course_sub_rel values('MScMathHS',1,'Mat1Sub1');
Insert into course_sub_rel values('MScMathHS',1,'Mat1Sub2');
Insert into course_sub_rel values('MScMathHS',1,'Mat1Sub3');
Insert into course_sub_rel values('MScMathHS',1,'Mat1Sub4');
Insert into course_sub_rel values('MScMathHS',1,'Mat1Sub5');
Insert into course_sub_rel values('MScMathHS',2,'Mat2Sub1');
Insert into course_sub_rel values('MScMathHS',2,'Mat2Sub2');
Insert into course_sub_rel values('MScMathHS',2,'Mat2Sub3');
Insert into course_sub_rel values('MScMathHS',2,'Mat2Sub4');
Insert into course_sub_rel values('MScMathHS',2,'Mat2Sub5');
Insert into course_sub_rel values('MScMathHS',3,'Mat3Sub1');
Insert into course_sub_rel values('MScMathHS',3,'Mat3Sub2');
Insert into course_sub_rel values('MScMathHS',3,'Mat3Sub3');
Insert into course_sub_rel values('MScMathHS',3,'Mat3Sub4');
Insert into course_sub_rel values('MScMathHS',3,'Mat3Sub5');
Insert into course_sub_rel values('MScMathHS',4,'Mat4Sub1');
Insert into course_sub_rel values('MScMathHS',4,'Mat4Sub2');
Insert into course_sub_rel values('MScMathHS',4,'Mat4Sub3');
Insert into course_sub_rel values('MScMathHS',4,'Mat4Sub4');
Insert into course_sub_rel values('MScMathHS',4,'Mat4Sub5');
Insert into course_sub_rel values('BECSE',1,'CSE1Sub1');
Insert into course_sub_rel values('BECSE',1,'CSE1Sub2');
Insert into course_sub_rel values('BECSE',1,'CSE1Sub3');
Insert into course_sub_rel values('BECSE',1,'CSE1Sub4');
Insert into course_sub_rel values('BECSE',1,'CSE1Sub5');
Insert into course_sub_rel values('BECSE',2,'CSE2Sub1');
Insert into course_sub_rel values('BECSE',2,'CSE2Sub2');
Insert into course_sub_rel values('BECSE',2,'CSE2Sub3');
Insert into course_sub_rel values('BECSE',2,'CSE2Sub4');
Insert into course_sub_rel values('BECSE',2,'CSE2Sub5');
Insert into course_sub_rel values('BECSE',3,'CSE3Sub1');
Insert into course_sub_rel values('BECSE',3,'CSE3Sub2');
Insert into course_sub_rel values('BECSE',3,'CSE3Sub3');
Insert into course_sub_rel values('BECSE',3,'CSE3Sub4');
Insert into course_sub_rel values('BECSE',3,'CSE3Sub5');
Insert into course_sub_rel values('BECSE',4,'CSE4Sub1');
Insert into course_sub_rel values('BECSE',4,'CSE4Sub2');
Insert into course_sub_rel values('BECSE',4,'CSE4Sub3');
Insert into course_sub_rel values('BECSE',4,'CSE4Sub4');
Insert into course_sub_rel values('BECSE',4,'CSE4Sub5');
Insert into course_sub_rel values('BECSE',5,'CSE5Sub1');
Insert into course_sub_rel values('BECSE',5,'CSE5Sub2');
Insert into course_sub_rel values('BECSE',5,'CSE5Sub3');
Insert into course_sub_rel values('BECSE',5,'CSE5Sub4');
Insert into course_sub_rel values('BECSE',5,'CSE5Sub5');
Insert into course_sub_rel values('BECSE',6,'CSE6Sub1');
Insert into course_sub_rel values('BECSE',6,'CSE6Sub2');
Insert into course_sub_rel values('BECSE',6,'CSE6Sub3');
Insert into course_sub_rel values('BECSE',6,'CSE6Sub4');
Insert into course_sub_rel values('BECSE',6,'CSE6Sub5');
Insert into course_sub_rel values('BECSE',7,'CSE7Sub1');
Insert into course_sub_rel values('BECSE',7,'CSE7Sub2');
Insert into course_sub_rel values('BECSE',7,'CSE7Sub3');
Insert into course_sub_rel values('BECSE',7,'CSE7Sub4');
Insert into course_sub_rel values('BECSE',7,'CSE7Sub5');
Insert into course_sub_rel values('BECSE',8,'CSE8Sub1');
Insert into course_sub_rel values('BECSE',8,'CSE8Sub2');
Insert into course_sub_rel values('BECSE',8,'CSE8Sub3');
Insert into course_sub_rel values('BECSE',8,'CSE8Sub4');
Insert into course_sub_rel values('BECSE',8,'CSE8Sub5');
Insert into course_sub_rel values('BAEngHS',1,'Eng1Sub1');
Insert into course_sub_rel values('BAEngHS',1,'Eng1Sub2');
Insert into course_sub_rel values('BAEngHS',1,'Eng1Sub3');
Insert into course_sub_rel values('BAEngHS',1,'Eng1Sub4');
Insert into course_sub_rel values('BAEngHS',1,'Eng1Sub5');
Insert into course_sub_rel values('BAEngHS',2,'Eng2Sub1');
Insert into course_sub_rel values('BAEngHS',2,'Eng2Sub2');
Insert into course_sub_rel values('BAEngHS',2,'Eng2Sub3');
Insert into course_sub_rel values('BAEngHS',2,'Eng2Sub4');
Insert into course_sub_rel values('BAEngHS',2,'Eng2Sub5');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub1');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub2');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub3');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub4');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub5');
Insert into course_sub_rel values('BAEngHS',3,'Eng3Sub6');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub1');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub2');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub3');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub4');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub5');
Insert into course_sub_rel values('BAEngHS',4,'Eng4Sub6');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub1');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub2');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub3');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub4');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub5');
Insert into course_sub_rel values('BAEngHS',5,'Eng5Sub6');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub1');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub2');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub3');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub4');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub5');
Insert into course_sub_rel values('BAEngHS',6,'Eng6Sub6');

-- Step 3 (Depicting the New course pgdca and its relation to the subjects )
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub1');
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub2');
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub3');
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub4');
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub5');
insert into course_sub_rel values('PGDCA', 1, 'PGD1Sub6');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub1');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub2');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub3');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub4');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub5');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub6');
insert into course_sub_rel values('PGDCA', 2, 'PGD2Sub7');

